### ISSUE TITLE
Can't use/build for Electron

### ISSUE THREAD

**Issue by Tim3Game** [kniffen/TruckSim-Telemetry#1]
Hello,
I want to use your 'app' in my Electron application, but can't get it running. I found something about [rebuilding the app for Electron](https://stackoverflow.com/a/36048721/11387983), but it's throwing an error. I tested it on NodeJS and it's working.

**Error log:**
```
PS C:\_PROGRAMING\Electron\truckz> npm run postinstall
npm WARN lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\node\bin\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> truckz@0.0.1 postinstall C:\_PROGRAMING\Electron\truckz
> electron-builder install-app-deps

Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • Unresolved node modules: register-scheme
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\node\bin\node.exe exited with code 1
Output:

> trucksim-telemetry@0.2.0 install C:\_PROGRAMING\Electron\truckz\node_modules\trucksim-telemetry
> node-gyp rebuild


C:\_PROGRAMING\Electron\truckz\node_modules\trucksim-telemetry>if not defined npm_config_node_gyp (node "C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  scsSDKTememetry.cc
  win_delay_load_hook.cc
C:\Users\Timothy Beihofner\.electron-gyp\iojs-2.0.18\x64\iojs.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x3E2676 [C:\_PROGRAMING\Electron\truckz\node_modules\trucksim-telemetry\build\scsSDKTememetry.vcxproj]

Error output:
npm WARN lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\node\bin\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Timothy Beihofner\\AppData\\Roaming\\npm\\node_modules\\node\\bin\\node.exe" "C:\\Users\\Timothy Beihofner\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\_PROGRAMING\Electron\truckz\node_modules\trucksim-telemetry
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trucksim-telemetry@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trucksim-telemetry@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TimBei\AppData\Roaming\npm-cache\_logs\2019-05-01T15_57_04_748Z-debug.log

    at ChildProcess.childProcess.once.code (C:\_PROGRAMING\Electron\truckz\node_modules\app-builder-lib\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:272:13)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at _rebuild (C:\_PROGRAMING\Electron\truckz\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\_PROGRAMING\Electron\truckz\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\_PROGRAMING\Electron\truckz\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (C:\_PROGRAMING\Electron\truckz\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\_PROGRAMING\Electron\truckz\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\_PROGRAMING\Electron\truckz\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at _installAppDeps (C:\_PROGRAMING\Electron\truckz\node_modules\electron-builder\out\cli\install-app-deps.js:176:26)
    at installAppDeps (C:\_PROGRAMING\Electron\truckz\node_modules\electron-builder\out\cli\install-app-deps.js:144:26)
    at then (C:\_PROGRAMING\Electron\truckz\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! truckz@0.0.1 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the truckz@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TimBei\AppData\Roaming\npm-cache\_logs\2019-05-01T15_57_04_797Z-debug.log
```
**2019-05-01T15_57_04_797Z-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Timothy Beihofner\\AppData\\Roaming\\npm\\node_modules\\node\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Timothy Beihofner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'postinstall' ]
2 info using npm@6.9.0
3 info using node@v9.8.0
4 verbose run-script [ 'postinstall' ]
5 info lifecycle truckz@0.0.1~postinstall: truckz@0.0.1
6 warn lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\node\bin\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
7 verbose lifecycle truckz@0.0.1~postinstall: unsafe-perm in lifecycle true
8 verbose lifecycle truckz@0.0.1~postinstall: PATH: C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\_PROGRAMING\Electron\truckz\node_modules\.bin;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\WinSCP\;C:\Program Files\Git\cmd;C:\Program Files (x86)\ZeroTier\One\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Timothy Beihofner\AppData\Local\Programs\Python\Python36;C:\_PROGRAMING\Android\SDK\platform-tools;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\FPC\3.0.4\bin\i386-Win32;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Timothy Beihofner\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\;C:\Users\Timothy Beihofner\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\_PROGRAMING\Android\_SDK\platform-tools;C:\Program Files (x86)\Yarn\bin\;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin;C:\Users\Timothy Beihofner\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\TimBei\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\TimBei\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\WinSCP\;C:\Program Files\Git\cmd;C:\Program Files (x86)\ZeroTier\One\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Timothy Beihofner\AppData\Local\Programs\Python\Python36;C:\_PROGRAMING\Android\SDK\platform-tools;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\FPC\3.0.4\bin\i386-Win32;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Timothy Beihofner\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\;C:\Users\Timothy Beihofner\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\_PROGRAMING\Android\_SDK\platform-tools;C:\Program Files (x86)\Yarn\bin\;C:\Users\TimBei\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\TimBei\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\TimBei\AppData\Roaming\npm\node_modules\.bin;C:\Users\TimBei\AppData\Local\Programs\Python\Python36;C:\Users\TimBei\AppData\Roaming\npm;C:\Users\Timothy Beihofner\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\Timothy Beihofner\AppData\Roaming\Dashlane\6.1907.0.17833\ucrt;C:\Users\Timothy Beihofner\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Qt;C:\Users\Timothy Beihofner\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Ssl;C:\Users\TimBei\AppData\Local\Yarn\bin
9 verbose lifecycle truckz@0.0.1~postinstall: CWD: C:\_PROGRAMING\Electron\truckz
10 silly lifecycle truckz@0.0.1~postinstall: Args: [ '/d /s /c', 'electron-builder install-app-deps' ]
11 silly lifecycle truckz@0.0.1~postinstall: Returned: code: 1  signal: null
12 info lifecycle truckz@0.0.1~postinstall: Failed to exec postinstall script
13 verbose stack Error: truckz@0.0.1 postinstall: `electron-builder install-app-deps`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Timothy Beihofner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid truckz@0.0.1
15 verbose cwd C:\_PROGRAMING\Electron\truckz
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Users\\Timothy Beihofner\\AppData\\Roaming\\npm\\node_modules\\node\\bin\\node.exe" "C:\\Users\\Timothy Beihofner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
18 verbose node v9.8.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error truckz@0.0.1 postinstall: `electron-builder install-app-deps`
22 error Exit status 1
23 error Failed at the truckz@0.0.1 postinstall script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kniffen** [comment]
This seems to be a [https://github.com/nodejs/node-gyp](node-gyp) issue
It's used to compile this module when you install it with npm, so you need to make sure you have the build tools installed (see install section in link above).

After you get that working though you may run into another issue as Electron may be using a separate version of Node than what's installed on your system.
To resolve this look into [electron-rebuild](https://github.com/electron/electron-rebuild).

Best of luck.

**Comment by Tim3Game** [comment]
Hello,
So I tried to reinstall node-gyp (because I already had it) and installed build tools, another time, and installed electron-rebuild, but I think I have something wrongly installed on my PC, so I decided to try it on my second PC. I copied my project (without node_modules) to my second PC, installed everything, run ``npm i`` and ``./node_modules/.bin/electron-rebuild.cmd`` (as it was said on their GitHub page), and no error. But when I tried to run my application, it "crashed" (or something in that matter) and I didn't knew why, because no error in the console. So I went to the ``node_modules/trucksim-telemetry`` folder and run ``node index.js`` and got this. Maybe it has nothing to do with it, but it's the only thing that came in my mind on what how to try to test it.

![image](https://user-images.githubusercontent.com/34278596/57103359-ce11c780-6d25-11e9-9d99-098315e0305f.png)

**Comment by kniffen** [comment]
When you run electron-rebuilt it rebuilds/compiles all modules to fit electron, thus you cannot run those modules with node anymore.

I did a test with electron and the only issue i ran into was a hard crash if the plugin was not installed and/or had never been used, as there was then no data to be found in the shared memory location.
Other than that it worked fine.

Your issue still seems related the compiling of the module however.
Did the installation of the build tools throw any errors?
I've ran into issues installing them before.

Also did you install the modules before running electron rebuild?
Steps should be
1. `npm install electron trucksim-telemetry`
2. `npm install --save-dev electron-rebuild`
3. `./node_modules/.bin/electron-rebuild`
4. `electron .`

**Comment by Tim3Game** [comment]
So, thanks to your test, I did test it with the game running, and... it worked. I stupidly never though of opening the game and then testing it, because I previously used the Telemetry in C# with an "module" and there it didn't needed the game to run, it simply didn't outputted anything. Could you please add something to prevent the hard crash, for instance test somehow the availability of the shared memory file and simply output some empty array or something? It would be really nice.

I didn't got any error with the installation of the build tools and I run the commands in the same order, but I think it has something to do me having installed python 3 and VS 2017 or something, and/or having the path set wrongly, so I will try to find the problem and I'll let you know.

**Comment by kniffen** [comment]
Hard crash issue fixed as of v0.2.1

I know node-gyp does not like Python 3 very much, and installing it and Pythion 2.7 will confuse it cause of the paths.
If i recall correctly, even if you uninstall Python 3 the path issue will remain.
So you'll have to fix that manually.

**Comment by Tim3Game** [comment]
Thanks

I actually changed the path, so it probably will be anything other then that, but I will check for differences between my main pc and second PC and see what else it can be, so if I fix it I will say.

**Comment by kniffen** [comment]
Closing issue for now as it can't be replicated.
